# .github/actions/update-aws-secret/action.yml
name: 'Update AWS Secret'
description: 'Crea un archivo temporal y actualiza un secreto en AWS Secrets Manager'
inputs:
  secret-arn:
    description: 'ARN del secreto en AWS Secrets Manager'
    required: true
  secret-content:
    description: 'Contenido del secreto a guardar'
    required: true
  secret-name:
    description: 'Nombre del archivo temporal (sin extensión)'
    required: false
    default: 'temp-secret'
  aws-region:
    description: 'Región de AWS'
    required: false
    default: 'us-east-1'

runs:
  using: 'composite'
  steps:
    - name: Create temporary secret file
      shell: bash
      run: |
        SECRET_CONTENT=$(cat << 'EOF'
        ${{ inputs.secret-content }}
        EOF
        )
        echo "$SECRET_CONTENT" > "${{ inputs.secret-name }}.txt"
        echo "Archivo temporal creado: ${{ inputs.secret-name }}.txt"
    
    - name: Update AWS Secret
      shell: bash
      run: |
        aws secretsmanager put-secret-value \
          --secret-id "${{ inputs.secret-arn }}" \
          --secret-string "file://${{ inputs.secret-name }}.txt" \
          --region "${{ inputs.aws-region }}"
        echo "Secreto actualizado exitosamente"
    
    - name: Clean up temporary file
      shell: bash
      if: always()
      run: |
        if [ -f "${{ inputs.secret-name }}.txt" ]; then
          rm "${{ inputs.secret-name }}.txt"
          echo "Archivo temporal eliminado"
        fi