AWSTemplateFormatVersion: '2010-09-09'

Description: OpenSearchService secrets

Resources:
  OpenSearchMasterUser:
    Type: 'AWS::SecretsManager::Secret'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: "OPENSEARCH_MASTER_USER"
      Description: "OpenSearch master user"

Outputs:
  OpenSearchMasterUserArn:
    Value: !Ref OpenSearchMasterUser
    Description: Secret ARN
    Export:
      Name: "secret-manager-OPENSEARCH-MASTER-USER-arn"