AWSTemplateFormatVersion: '2010-09-09'

Description: OpenSearchService secrets

Parameters:

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: 'Select the default VPC'

  CIDRblock:
    Type: String
    Description: The CIDR block for the VPC (e.g., 10.0.0.0/16).
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'Select 2 or more subnets from the default VPC'

Resources:
  OpenSearchMasterUser:
    Type: 'AWS::SecretsManager::Secret'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: "OPENSEARCH_MASTER_USER"
      Description: "OpenSearch master user"

  SecretManagerVPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPCId
      GroupName: SecretManager-VPCEndpoint-SecurityGroup
      GroupDescription: "Secret Manager VPC Endpoint security group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref CIDRblock

  # VPC endpoint to get access from VPC resources
  SecretManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds: !Ref SubnetIds
      SecurityGroupIds:
        - !Ref SecretManagerVPCEndpointSecurityGroup

Outputs:
  OpenSearchMasterUserArn:
    Value: !Ref OpenSearchMasterUser
    Description: Secret ARN
    Export:
      Name: "secret-manager-OPENSEARCH-MASTER-USER-arn"