AWSTemplateFormatVersion: '2010-09-09'

Description: OpenSearchServiceDomain resource
Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: 'Select the default VPC'

  CIDRblock:
    Type: String
    Description: The CIDR block for the VPC (e.g., 10.0.0.0/16).
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'Select 2 or more subnets from the default VPC'

  DomainName:
    Type: String
    Default: 'my-opensearch'
    Description: 'OpenSearch domain name'

Resources:
  OpenSearchDomainSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "OpenSearch-${DomainName}-SecurityGroup"
      GroupDescription: 'Open Search security group'
      VpcId: !Ref VPCId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref CIDRblock

  OpenSearchKMSKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Description: A symmetric encryption KMS key to use in OpenSearch domain
      EnableKeyRotation: true
      PendingWindowInDays: 30
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:user/jean'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'

  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      DomainName: !Ref DomainName
      EngineVersion: 'OpenSearch_2.3'
      ClusterConfig:
        InstanceType: 't3.small.search'
        InstanceCount: 1
      EBSOptions:
        EBSEnabled: true
        VolumeType: 'gp3'
        VolumeSize: 20
      VPCOptions:
        SecurityGroupIds:
          - !Ref OpenSearchDomainSecurityGroup
        SubnetIds: !Ref SubnetIds
      AdvancedSecurityOptions:
        Enabled: true
        AnonymousAuthEnabled: false
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: !Join [ "", [ "{{resolve:secretsmanager:", Fn::ImportValue: "secret-manager-OPENSEARCH-MASTER-USER-arn", ':SecretString:username}}' ] ]
          MasterUserPassword: !Join [ "", [ "{{resolve:secretsmanager:", Fn::ImportValue: "secret-manager-OPENSEARCH-MASTER-USER-arn", ':SecretString:password}}' ] ]
      NodeToNodeEncryptionOptions:
        Enabled: true
      EncryptionAtRestOptions:
        Enabled: true
        KmsKeyId: !Ref OpenSearchKMSKey
      DomainEndpointOptions:
        EnforceHTTPS: true
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: !Sub 'arn:${AWS::Partition}:es:${AWS::Region}:${AWS::AccountId}:domain/${DomainName}/*'
  
  OpenSearchAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: OpenSearchS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetBucketLocation"
                  - "s3:ListBucketMultipartUploads"
                  - "s3:ListBucketVersions"
                Resource: "arn:aws:s3:::dev-data-*"
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                  - "s3:AbortMultipartUpload"
                  - "s3:ListMultipartUploadParts"
                Resource: "arn:aws:s3:::dev-data-*"

Outputs:
  OpenSearchEndpoint:
    Value: !Sub 'https://${OpenSearchDomain.DomainEndpoint}'
    Export:
      Name: 'OpenSearch-Endpoint'

  OpenSearchArn:
    Value: !GetAtt OpenSearchDomain.DomainArn
    Export:
      Name: 'OpenSearch-Arn'

  OpenSearchDomainSecurityGroupId:
    Value: !Ref OpenSearchDomainSecurityGroup
    Export:
      Name: 'OpenSearch-SecurityGroup'

  OpenSearchAssumeRoleArn:
    Value: !GetAtt OpenSearchAssumeRole.Arn
    Export:
      Name: 'OpenSearch-Assume-Role'

  VPCId:
    Value: !Ref VPCId
    Export:
      Name: !Sub '${AWS::StackName}-VPC'